[package]
name = "scheme-engine"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bench]]
name = "fibonacci"
harness = false

[dev-dependencies]
criterion = "0.5"

[dependencies]
smol_str = "0.1"
